// Generated by gencpp from file my_ros_msgs/hw2.msg
// DO NOT EDIT!


#ifndef MY_ROS_MSGS_MESSAGE_HW2_H
#define MY_ROS_MSGS_MESSAGE_HW2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_msgs
{
template <class ContainerAllocator>
struct hw2_
{
  typedef hw2_<ContainerAllocator> Type;

  hw2_()
    : message()
    , command(0)  {
    }
  hw2_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , command(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef uint8_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::my_ros_msgs::hw2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_msgs::hw2_<ContainerAllocator> const> ConstPtr;

}; // struct hw2_

typedef ::my_ros_msgs::hw2_<std::allocator<void> > hw2;

typedef boost::shared_ptr< ::my_ros_msgs::hw2 > hw2Ptr;
typedef boost::shared_ptr< ::my_ros_msgs::hw2 const> hw2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_msgs::hw2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_msgs::hw2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_ros_msgs': ['/home/ros-student/catkin_ws/src/my_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::hw2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::hw2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::hw2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::hw2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::hw2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::hw2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_msgs::hw2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "180698a25f3b4080cbf72c632befde42";
  }

  static const char* value(const ::my_ros_msgs::hw2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x180698a25f3b4080ULL;
  static const uint64_t static_value2 = 0xcbf72c632befde42ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_msgs::hw2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_msgs/hw2";
  }

  static const char* value(const ::my_ros_msgs::hw2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_msgs::hw2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
uint8 command\n\
";
  }

  static const char* value(const ::my_ros_msgs::hw2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_msgs::hw2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hw2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_msgs::hw2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_msgs::hw2_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_MSGS_MESSAGE_HW2_H
