// Generated by gencpp from file my_ros_msgs/my_IoT.msg
// DO NOT EDIT!


#ifndef MY_ROS_MSGS_MESSAGE_MY_IOT_H
#define MY_ROS_MSGS_MESSAGE_MY_IOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_msgs
{
template <class ContainerAllocator>
struct my_IoT_
{
  typedef my_IoT_<ContainerAllocator> Type;

  my_IoT_()
    : temperature(0)
    , humidity(0)
    , status(false)
    , location()  {
    }
  my_IoT_(const ContainerAllocator& _alloc)
    : temperature(0)
    , humidity(0)
    , status(false)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _temperature_type;
  _temperature_type temperature;

   typedef uint8_t _humidity_type;
  _humidity_type humidity;

   typedef uint8_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::my_ros_msgs::my_IoT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_msgs::my_IoT_<ContainerAllocator> const> ConstPtr;

}; // struct my_IoT_

typedef ::my_ros_msgs::my_IoT_<std::allocator<void> > my_IoT;

typedef boost::shared_ptr< ::my_ros_msgs::my_IoT > my_IoTPtr;
typedef boost::shared_ptr< ::my_ros_msgs::my_IoT const> my_IoTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_msgs::my_IoT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_msgs::my_IoT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_ros_msgs': ['/home/ros-student/catkin_ws/src/my_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::my_IoT_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::my_IoT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::my_IoT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6edeaa3532f795fb8e5e11041bdf1b5";
  }

  static const char* value(const ::my_ros_msgs::my_IoT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6edeaa3532f795fULL;
  static const uint64_t static_value2 = 0xb8e5e11041bdf1b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_msgs/my_IoT";
  }

  static const char* value(const ::my_ros_msgs::my_IoT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 temperature\n\
uint8 humidity\n\
bool status\n\
string location\n\
";
  }

  static const char* value(const ::my_ros_msgs::my_IoT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature);
      stream.next(m.humidity);
      stream.next(m.status);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_IoT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_msgs::my_IoT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_msgs::my_IoT_<ContainerAllocator>& v)
  {
    s << indent << "temperature: ";
    Printer<int64_t>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.humidity);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_MSGS_MESSAGE_MY_IOT_H
